all: exercicio_5.c exercicio_4.c exercicio_3.c exercicio_2_3.c exercicio_2_2.c exercicio_2_1.c exercicio_1.c
	gcc exercicio_5.c -pthread -lm -o exercicio_5
	gcc exercicio_4.c -pthread -lm -o exercicio_4
	gcc exercicio_3.c -pthread -lm -o exercicio_3
	gcc exercicio_2_3.c -pthread -lm -o exercicio_2_3
	gcc exercicio_2_2.c -pthread -lm -o exercicio_2_2
	gcc exercicio_2_1.c -pthread -lm -o exercicio_2_1
	gcc exercicio_1.c -pthread -lm -o exercicio_1	

