all: programa_exercicio1 programa_exercicio3 programa_exercicio4 programa_exercicio5 programa_exercicio6

programa_exercicio1: programa_exercicio1.c func.h 
	gcc -g -Wall -O2 -D_REENTRANT -D_GNU_SOURCE -lpthread -pthread -lrt programa_exercicio1.c func.o -o programa_exercicio1

programa_exercicio3: programa_exercicio3.c func.h 
	gcc -g -Wall -O2 -D_REENTRANT -D_GNU_SOURCE -lpthread -pthread -lrt programa_exercicio3.c func.o -o programa_exercicio3

programa_exercicio4: programa_exercicio4.c func.h 
	gcc -g -Wall -O2 -D_REENTRANT -D_GNU_SOURCE -lpthread -pthread -lrt programa_exercicio4.c func.o -o programa_exercicio4

programa_exercicio5: programa_exercicio5.c func2.h
	gcc -Wall -O2 -D_REENTRANT -D_GNU_SOURCE -lpthread -pthread -lrt programa_exercicio5.c func2.o -o programa_exercicio5
		
programa_exercicio6: programa_exercicio6.c func.h 
	gcc -g -Wall -O2 -D_REENTRANT -D_GNU_SOURCE -lpthread -pthread -lrt programa_exercicio6.c func.o -o programa_exercicio6
